version: '3'
services:  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped

    ports:
      - 9117:9117

    volumes:
      - $PWD/configs/jackett:/config

    environment:
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000

